version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8080:80"

    environment:
      MYSQL_USER: votify_user
      MYSQL_PASSWORD: votify_password
      MYSQL_DATABASE: votify_system
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: votify_system
      MYSQL_USER: votify_user
      MYSQL_PASSWORD: votify_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
